apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-restaurant-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-restaurant-app
  template:
    metadata:
      labels:
        app: my-restaurant-app
    spec:
      containers:
      - name: my-restaurant-app
        image: thanishma/my-restaurant-app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: my-restaurant-app-service
spec:
  selector:
    app: my-restaurant-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
