apiVersion: v1
kind: Service
metadata:
  name: my-restaurant-app-service
spec:
  selector:
    app: my-restaurant-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
